/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721 from "./erc721";
export type { erc721 };
export type { ERC721Factory } from "./ERC721Factory";
export type { MinimalProxy2 } from "./MinimalProxy2";
